### ISSUE TITLE
Invalid certificate on the nodejs.africa website

### ISSUE THREAD

**Issue by yaaminu** [nodejsafrica/nodejsafrica#11]
I just visited the website[nodejs.africa](nodejs.africa) and my browser prompted me of an invalid certificate. I suspect this is likely a server misconfiguration. 

Browsers: Firefox 67.0, chrome 74.0 
OS: MacOS Mojave

Thanks

**Comment by codeekage** [comment]
Thank you @yaaminu  the issue has been resolved
