### ISSUE TITLE
Documentation and Information Management

### ISSUE THREAD

**Issue by codeekage** [nodejsafrica/nodejsafrica#3]
As an organization, decisions will always be made and this decision or contributions to the organization should be properly documented and related to the public.

I think this should be one of the vital discussions during the first meeting, assigning the role to someone to take proper documentation of final decisions made by this body.

The role of this individual includes writing markdowns for the README.md file and Wiki on the repo and also, markups for the webpages if necessary.

**Comment by theodoraisola** [comment]
I am taking up this role. Kindly communicate information for documentation as the need arises.
