### ISSUE TITLE
Add as a member

### ISSUE THREAD

**Issue by samie820** [nodejsafrica/nodejsafrica#7]

**Comment by inidaname** [comment]
@codeekage

**Comment by codeekage** [comment]
@samie820 can you please give little details about you and what role you can play in Node.js Africa 🤘

**Comment by samie820** [comment]
@codeekage I am a software developer based in Abuja, also part of the NodeJS mentorship program as a mentor (Sammy), we have spoken on the slack channel.  I mainly work with the MERN stack,  I have been talking with Hassan and I want to help in growing the nodeJS community both in Abuja and Nigeria as a whole, first by helping in the organization of regular meet-ups to train "node newbies" based on the node school curriculum.

**Comment by samie820** [comment]
Hi @codeekage, I haven't gotten any feedback from you...

**Comment by codeekage** [comment]
Done! Welcome bro!

**Comment by codeekage** [comment]
@samie820  please add your name as a contributor in @nodejsafrica/members

**Comment by samie820** [comment]
OK bro,  will do that soon
